{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .repoUrl | quote }}
    {{- if .chart }}
    chart: {{ .chart | quote }}
    targetRevision: {{ .version | quote }}
    helm:
      releaseName: {{ .name | quote }}
      {{- with .values }}
      values: |
{{ . | indent 8 }}
      {{- end }}
    {{- else }}
    targetRevision: {{ .branch | default "main" | quote }}
    path: {{ .path | quote }}
    {{- if .values }}
    helm:
      releaseName: {{ .name | quote }}
      values: |
{{ .values | indent 8 }}
    {{- end }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace | quote }}
  {{- with .ignoreDifferences }}
  ignoreDifferences:
{{ toYaml . | indent 4 }}
  {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
{{- end }}
