---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: AgBle466SzvJSmtoGz2vw/ffA2eIi7/eupjMGJIdqffTWuwsPy4qkKAwPz3Li0K+jbF2NNFFSCRCVslztwLoslv9/8qzTERd1frRVjF+PYPIUn7KJUr+9dqfl1M9aHO8GrJRaKNrm+mCSJ3MFgTk8lXJQvQwVpXSsez0TwKqtpgNa4hGR0PZhx6ZLEeMyI9zk0Bts19oEJvXgSRRrdZCBveuUHR4P3b+aGGA0L+imeRUJDr3dEMwHnbLeaPir2WrHNhQ6vpYIMfvaYhQp72KnMna6Jlp5duEGzlZWkZh0/C4gdeYiuVZD+c+2btuqT8yvq7VMDo7dZu8QZ7BoUIJ3yrJEMbx/tQXSMeUkPZhp0dQpN/X80co7PuS5rVCOkTPe2S0x5vQI3uYOssNW7BIAdVE+O6YKRMI74gkEqxZglzHslcPGeSLGrABOWQSwcAU5QGme+LjhTBozXzjJDyLyOkIRMUH4HoEsBlIOau4ZScr61l/As1RGq0TbuTc/gyPoMn7oLHVIrt+5jARM7FuPyX7A6H4VpLu80wHxeF/eS43XDoOzabsWtjfddMi1jsEHWVqo4M+Ywclbb/Mj2cLjr1g32aN9UKY9uCo3sEb5mkMwplvop46L714Jig3q9i44YU3m0hPtkMzkhLsbdmlcXOwOi4BK/lWSM9tBJALkPdllKwXWNHGbl9SGKpnFK0Jj9Xx0IFGHGZF+auJzabXuAyRINGzrUEDVKsWtvq6lILEyw==
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
