apps:
  - name: podinfo
    repoUrl: https://github.com/stefanprodan/podinfo
    branch: master
    path: kustomize
    namespace: podinfo

  - name: sealed-secrets
    repoUrl: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    version: 2.16.1
    namespace: sealed-secrets
    values: |
      fullnameOverride: sealed-secrets-controller

  - name: pihole-secrets
    repoUrl: https://github.com/ryana-0154/homelab-gitops
    branch: main
    path: secrets/pihole
    namespace: pihole

  - name: pihole
    repoUrl: https://github.com/ryana-0154/pihole-helm
    branch: main
    path: .
    namespace: pihole
    values: |
      existingSecret: pihole-admin

  - name: envoy-gateway
    repoUrl: docker.io/envoyproxy
    chart: gateway-helm
    version: v1.4.0
    namespace: envoy-gateway-system

  - name: cert-manager
    repoUrl: https://charts.jetstack.io
    chart: cert-manager
    version: v1.16.2
    namespace: cert-manager
    values: |
      crds:
        enabled: true

  - name: cert-manager-issuers
    repoUrl: https://github.com/ryana-0154/homelab-gitops
    branch: main
    path: certs
    namespace: cert-manager

  - name: gateway-resources
    repoUrl: https://github.com/ryana-0154/homelab-gitops
    branch: main
    path: gateway
    namespace: envoy-gateway-system
